// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTUfKx6oRGnFWHYRIeLVf-s2CPfFmsfZA',
    appId: '1:775630117709:web:e0c6ad310ad688cf203504',
    messagingSenderId: '775630117709',
    projectId: 'biologychatbot',
    authDomain: 'biologychatbot.firebaseapp.com',
    storageBucket: 'biologychatbot.appspot.com',
    measurementId: 'G-TYFZFN8XP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1P44f1x0FcjcFbU7g_-aVpwMxm7woYbA',
    appId: '1:775630117709:android:16a6a5ba16a08945203504',
    messagingSenderId: '775630117709',
    projectId: 'biologychatbot',
    storageBucket: 'biologychatbot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPtO1JYqZaKPqyi7jwdLiHh_mwAeS0tA',
    appId: '1:775630117709:ios:9afc8c95e8e8b31e203504',
    messagingSenderId: '775630117709',
    projectId: 'biologychatbot',
    storageBucket: 'biologychatbot.appspot.com',
    iosBundleId: 'com.example.biologychatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPtO1JYqZaKPqyi7jwdLiHh_mwAeS0tA',
    appId: '1:775630117709:ios:9afc8c95e8e8b31e203504',
    messagingSenderId: '775630117709',
    projectId: 'biologychatbot',
    storageBucket: 'biologychatbot.appspot.com',
    iosBundleId: 'com.example.biologychatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTUfKx6oRGnFWHYRIeLVf-s2CPfFmsfZA',
    appId: '1:775630117709:web:4df46b2a120de47f203504',
    messagingSenderId: '775630117709',
    projectId: 'biologychatbot',
    authDomain: 'biologychatbot.firebaseapp.com',
    storageBucket: 'biologychatbot.appspot.com',
    measurementId: 'G-DZJM5VRNBR',
  );

}